server:
  servlet:
    context-path: /chco/api
  port: 10400
spring:
  application:
    name:  notification-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: high-user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${application.email}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
application:
  email: caitocd@gmail.com