server:
  servlet:
    context-path: /chco/api
  port: 10300
spring:
  application:
    name:  product-service
  datasource:
    url: jdbc:mysql://localhost:3306/chemical_co
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
